Repository ucsc/ucsc-custom-functionality, pull requests merged in 2025-04, with the labels that each got.

#63 fix: 🚑️ Update allowed taxonomies on News Block selector to include tags
  src/Blocks/News_Block.php
Labels: bug

#71 Feat: 🎉 Add ability to choose 3, 6, or 9 posts to be displayed in the News Block
  src/Blocks/News_Block.php
  src/Components/News_Block_Controller.php
Labels: change, enhancement

#73 Fix: 🚑 Edit Post Terms Block method to only target the Single Post Template
  src/Template/Blocks_Render.php
Labels: change
